## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  teamcity:
    address: ":8111"
  agents:
    address: ":9090"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false